use crate::Console;

pub fn get_hardcoded_consoles() -> Vec<Console> {
    vec![
        Console {
            id: "nes".to_string(),
            name: "Nintendo Entertainment System".to_string(),
            manufacturer: "Nintendo".to_string(),
            year: 1985,
        },
        Console {
            id: "snes".to_string(),
            name: "Super Nintendo Entertainment System".to_string(),
            manufacturer: "Nintendo".to_string(),
            year: 1990,
        },
        Console {
            id: "n64".to_string(),
            name: "Nintendo 64".to_string(),
            manufacturer: "Nintendo".to_string(),
            year: 1996,
        },
        Console {
            id: "gamecube".to_string(),
            name: "Nintendo GameCube".to_string(),
            manufacturer: "Nintendo".to_string(),
            year: 2001,
        },
        Console {
            id: "wii".to_string(),
            name: "Nintendo Wii".to_string(),
            manufacturer: "Nintendo".to_string(),
            year: 2006,
        },
        Console {
            id: "wiiu".to_string(),
            name: "Nintendo Wii U".to_string(),
            manufacturer: "Nintendo".to_string(),
            year: 2012,
        },
        Console {
            id: "switch".to_string(),
            name: "Nintendo Switch".to_string(),
            manufacturer: "Nintendo".to_string(),
            year: 2017,
        },
        Console {
            id: "gb".to_string(),
            name: "Game Boy".to_string(),
            manufacturer: "Nintendo".to_string(),
            year: 1989,
        },
        Console {
            id: "gbc".to_string(),
            name: "Game Boy Color".to_string(),
            manufacturer: "Nintendo".to_string(),
            year: 1998,
        },
        Console {
            id: "gba".to_string(),
            name: "Game Boy Advance".to_string(),
            manufacturer: "Nintendo".to_string(),
            year: 2001,
        },
        Console {
            id: "ds".to_string(),
            name: "Nintendo DS".to_string(),
            manufacturer: "Nintendo".to_string(),
            year: 2004,
        },
        Console {
            id: "3ds".to_string(),
            name: "Nintendo 3DS".to_string(),
            manufacturer: "Nintendo".to_string(),
            year: 2011,
        },
        Console {
            id: "sg1000".to_string(),
            name: "SG-1000".to_string(),
            manufacturer: "Sega".to_string(),
            year: 1983,
        },
        Console {
            id: "mastersystem".to_string(),
            name: "Sega Master System".to_string(),
            manufacturer: "Sega".to_string(),
            year: 1985,
        },
        Console {
            id: "genesis".to_string(),
            name: "Sega Genesis".to_string(),
            manufacturer: "Sega".to_string(),
            year: 1988,
        },
        Console {
            id: "segacd".to_string(),
            name: "Sega CD".to_string(),
            manufacturer: "Sega".to_string(),
            year: 1991,
        },
        Console {
            id: "sega32x".to_string(),
            name: "Sega 32X".to_string(),
            manufacturer: "Sega".to_string(),
            year: 1994,
        },
        Console {
            id: "gamegear".to_string(),
            name: "Game Gear".to_string(),
            manufacturer: "Sega".to_string(),
            year: 1990,
        },
        Console {
            id: "pico".to_string(),
            name: "Sega Pico".to_string(),
            manufacturer: "Sega".to_string(),
            year: 1993,
        },
        Console {
            id: "saturn".to_string(),
            name: "Sega Saturn".to_string(),
            manufacturer: "Sega".to_string(),
            year: 1994,
        },
        Console {
            id: "dreamcast".to_string(),
            name: "Sega Dreamcast".to_string(),
            manufacturer: "Sega".to_string(),
            year: 1998,
        },
        Console {
            id: "ps1".to_string(),
            name: "PlayStation".to_string(),
            manufacturer: "Sony".to_string(),
            year: 1994,
        },
        Console {
            id: "ps2".to_string(),
            name: "PlayStation 2".to_string(),
            manufacturer: "Sony".to_string(),
            year: 2000,
        },
        Console {
            id: "ps3".to_string(),
            name: "PlayStation 3".to_string(),
            manufacturer: "Sony".to_string(),
            year: 2006,
        },
        Console {
            id: "ps4".to_string(),
            name: "PlayStation 4".to_string(),
            manufacturer: "Sony".to_string(),
            year: 2013,
        },
        Console {
            id: "ps5".to_string(),
            name: "PlayStation 5".to_string(),
            manufacturer: "Sony".to_string(),
            year: 2020,
        },
        Console {
            id: "psp".to_string(),
            name: "PlayStation Portable".to_string(),
            manufacturer: "Sony".to_string(),
            year: 2004,
        },
        Console {
            id: "psvita".to_string(),
            name: "PlayStation Vita".to_string(),
            manufacturer: "Sony".to_string(),
            year: 2011,
        },
        Console {
            id: "xbox".to_string(),
            name: "Xbox".to_string(),
            manufacturer: "Microsoft".to_string(),
            year: 2001,
        },
        Console {
            id: "xbox360".to_string(),
            name: "Xbox 360".to_string(),
            manufacturer: "Microsoft".to_string(),
            year: 2005,
        },
        Console {
            id: "xboxone".to_string(),
            name: "Xbox One".to_string(),
            manufacturer: "Microsoft".to_string(),
            year: 2013,
        },
        Console {
            id: "xboxseries".to_string(),
            name: "Xbox Series X/S".to_string(),
            manufacturer: "Microsoft".to_string(),
            year: 2020,
        },
    ]
}
